# -*- coding: utf-8 -*-
"""vector_stores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SoGQfqStXfgebsXzjAxz_5xyo_9C8CBK
"""

pip install -U transformers langchain chromadb pypdf
print("done!")

pip install langchain_huggingface

from langchain_huggingface import HuggingFaceEmbeddings
embeddings= HuggingFaceEmbeddings(
    model_name='sentence-transformers/all-MiniLM-L6-v2',
    #dimensions=300
)

from langchain.schema import Document
doc1= Document(page_content="The octopus wore a monocle while conducting a jazz orchestra underwater", metacontent="xyz",id=1)
doc2= Document(page_content="A mailbox in Nebraska suddenly started spitting out fortune cookies.", metacontent="xyz", id=2)
doc3= Document(page_content="Every Tuesday, the moon sends secret Morse code to a potato farm in Peru.", metacontent="xyz", id=3)
doc4= Document(page_content="The refrigerator screamed in binary when someone tried to store a lava lamp inside it.", metacontent="xyz", id=4)

docs=[doc1,doc2,doc3,doc4]

pip install langchain_chroma

from langchain_chroma import Chroma
vector_store= Chroma(
    embedding_function= embeddings,
    persist_directory="database",
    collection_name="docs"
)

from uuid import uuid4
uuids = [str(uuid4()) for _ in range(len(docs))]

vector_store.add_documents(documents=docs, id= uuids)

#query
#1.similarity search
results = vector_store.similarity_search(
    "where is the mailbox located and what happens with it?",
    k=1

)
for res in results:
    print(f"* {res.page_content} [{res.metadata}]")

#2. similarity search by score
results = vector_store.similarity_search_with_score(
    "what did the octopus wore?",
    k=1
)
print(results)
for res, score in results:
    print(f"* [SIM={score:3f}] {res.page_content} [{res.metadata}]")

#search by vector
results = vector_store.similarity_search_by_vector(
    embedding=embeddings.embed_query("what does the refrigerator say!"),
    k=1
)
for doc in results:
    print(f"* {doc.page_content} [{doc.metadata}]")

