# -*- coding: utf-8 -*-
"""ToolCalllling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RlOOBAoyLubTYXYyAzc1zjJZq5SQRoZ2
"""



from dotenv import load_dotenv
load_dotenv()

api= os.getenv("GOOGLE_API_KEY")

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, AIMessage
import requests

"""Tool Creation"""

#tool creation

@tool
def add(a:int, b:int)->int:
  """Adds the given 2 integer numbers and returns their sum """
  return a+b

print(add.invoke({"a":12,"b":67}))

print(add.name)
print(add.description)
print(add.args)

import os
os.environ["GOOGLE_API_KEY"]= api
chatmodel= ChatGoogleGenerativeAI(
    model= "gemini-2.5-flash",
    temperature= 0.8
)

"""Tool Binding"""

llm_with_tool= chatmodel.bind_tools([add])

"""Tool Calling"""

msg= []
query= HumanMessage("What is the sum of 12 and 178")
msg.append(query)
msg

response= llm_with_tool.invoke(msg)
msg.append(response)
print(msg)

"""Tool Execution"""

calls= response.tool_calls[0]
print(calls)
msg.append((add.invoke(calls)))
msg

llm_with_tool.invoke(msg).content