# -*- coding: utf-8 -*-
"""AIAgentLangChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FJeTxpXLsjylJOfzgZk5JtlvDa19GGNY
"""

from google.colab import userdata
api= userdata.get('GOOGLE_API_KEY')

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
import requests
import os

os.environ['GOOGLE_API_KEY']=api

llm= ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.6

)

from langchain.agents import create_react_agent, AgentExecutor
from langchain import hub

prompt= hub.pull("hwchase17/react")

@tool
def search(query:str):
  """ Tool used for searching over the Internet for the query provided by the user """
  from ddgs import DDGS
  client= DDGS()
  result= client.text(f"{query}", max_results=4)
  return(result[0]['body'])

agent= create_react_agent(
    llm= llm,
    tools=[search],
    prompt=prompt
)

agent_executer= AgentExecutor(
    agent= agent,
    tools=[search],
    verbose= True
)

result= agent_executer.invoke({"input": "What's the Captial of UttarPradesh"})
print(result)

